name: Extract ZIP File

on:
  push:
    paths:
      - 'your-file.zip'  # Replace with the name of your ZIP file
  
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Unzip the file
        run: |
          mkdir extracted
          unzip your-file.zip -d extracted/
      
      - name: Commit extracted files
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Extract ZIP file"
          git push
